name: Deploy Twin AI Docs to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build VitePress site
      run: npm run docs:build
      
    - name: Create package.json for Vercel
      run: |
        cat > docs/.vitepress/dist/package.json << 'EOF'
        {
          "name": "twin-ai-docs",
          "version": "1.0.0",
          "scripts": {
            "build": "echo 'Already built'",
            "start": "echo 'Static files'"
          },
          "dependencies": {}
        }
        EOF
        
    - name: Create vercel.json for static deployment
      run: |
        cat > docs/.vitepress/dist/vercel.json << 'EOF'
        {
          "version": 2,
          "builds": [
            {
              "src": "**/*",
              "use": "@vercel/static"
            }
          ]
        }
        EOF
      
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Deploy to Vercel with CLI
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        cd docs/.vitepress/dist
        npx vercel --token=$VERCEL_TOKEN --prod --yes --confirm
