name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 6 * * *'  # Chạy mỗi ngày lúc 6h sáng
  workflow_dispatch:  # Cho phép kích hoạt thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout fork
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/BachKhoiMaoGia/NewDocsTwin.git
        git fetch upstream
    
    - name: Sync with upstream
      run: |
        git checkout main
        git rebase upstream/main || git merge upstream/main --allow-unrelated-histories
    
    - name: Push changes
      run: git push origin main
